name: Manual Run Test

on:
  workflow_dispatch:

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Download package.json
        run: wget https://github.com/Script-Hub-Org/Script-Hub/raw/main/package.json -O package.json

      - name: Check if package.json exists and is not empty
        run: |
          if [ ! -s package.json ]; then
            echo "package.json is missing or empty!"
            exit 1
          fi

      - name: Install dependencies
        run: npm install

      - name: Run Test Script
        run: node Scripts/Test.js
