name: Convert Modules

on:
  schedule:
    - cron: '0 0 * * *' # 每天执行一次
  workflow_dispatch: # 手动触发

jobs:
  update-snippet:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download snippets and prepare variables
      id: download-and-prepare
      run: |
        mkdir -p Original
        README_CONTENT=""
        FILES_LIST=""
        declare -A file_map
        while read -r url; do
          [[ "$url" =~ ^#.*$ || -z "$url" ]] && continue  # 忽略空行和注释
          
          author=$(echo "$url" | awk -F'/' '{print $4}')
          filename=$(basename "$url")
          filename_no_ext=$(basename "$url" | cut -d'.' -f1)
          extension="${filename##*.}"
          
          # 处理文件重命名
          if [[ -n "${file_map["$author/$filename_no_ext"]}" ]]; then
            count=2
            new_filename="${filename_no_ext}-${count}.${extension}"
            while [[ -n "${file_map["$author/$new_filename"]}" ]]; do
              count=$((count + 1))
              new_filename="${filename_no_ext}-${count}.${extension}"
            done
            filename="$new_filename"
          fi
          
          # 创建作者文件夹
          mkdir -p "Original/$author"
          file_path="Original/$author/$filename"
          curl -L -o "$file_path" "$url"
          
          # 更新文件名映射
          file_map["$author/$filename_no_ext"]="$file_path"

          README_CONTENT="${README_CONTENT}\n- **${filename_no_ext}**: Converted from [${author} ${filename_no_ext}](${url})"
          
          hostnames=$(grep -v '^#' "$file_path" | grep 'hostname = ' | awk -F'hostname = ' '{print $2}' | tr '\n' ', ' | sed 's/, $//')
          comment="# ${filename_no_ext} // ${hostnames}"
          FILES_LIST="${FILES_LIST}\n${file_path};${author};${filename_no_ext};${comment}"
        done < Links/Modules-Links.txt

    - name: Convert snippets
      run: |
        IFS=$'\n'
        for file_info in $FILES_LIST; do
          # 跳过空行
          [ -z "$file_info" ] && continue
          file_path=$(echo $file_info | cut -d';' -f1)
          author=$(echo $file_info | cut -d';' -f2)
          module_name=$(echo $file_info | cut -d';' -f3)
          comment=$(echo $file_info | cut -d';' -f4)
          bash Scripts/Convert-Modules.sh "$file_path" "$module_name" "$comment"
        done

    - name: Create README in Modules directory
      run: |
        echo "# Modules for Surge and Loon" > Modules/README.md
        echo "" >> Modules/README.md
        echo "This directory contains converted modules from various sources, compatible with Surge and Loon." >> Modules/README.md
        echo "" >> Modules/README.md
        echo "## Sources" >> Modules/README.md
        echo "" >> Modules/README.md
        echo -e "$README_CONTENT" >> Modules/README.md

    - name: Commit and Push changes
      run: |
        git config --local user.name "ifflagged"
        git config --local user.email "qibo.sign@outlook.com"
        git add .
        if git diff --cached --quiet; then
          echo "No changes detected"
        else
          git commit -m "Update Modules"
          git push
        fi

    - name: Send TG Notification
      run: |
        # 检查是否存在上一个提交
        if git rev-parse --verify HEAD^1 >/dev/null 2>&1; then
          UPDATED_FILES=$(git diff --name-only HEAD^1 HEAD Modules/)
        else
          UPDATED_FILES=$(git diff --name-only HEAD Modules/)
        fi

        if [ -n "$UPDATED_FILES" ]; then
          MESSAGE="The following files have been updated:\n"
          GITHUB_URL="https://github.com/ifflagged/BaDaBaBaBa/blob/main/"
          while read -r file; do
            # 去掉 'Modules/' 前缀
            display_name=$(echo "$file" | sed 's/Modules\///')
            # 生成完整链接
            file_url="${GITHUB_URL}${file}"
            # 生成 markdown 格式的超链接
            MESSAGE="${MESSAGE}[${display_name}](${file_url})\n"
          done <<< "$UPDATED_FILES"

          # 使用 echo -e 处理换行符并发送通知
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TG_ID }} \
            -d text="$(echo -e "$MESSAGE")" \
            -d parse_mode=Markdown
        else
          echo "No files were updated, no notification sent."
        fi
