name: Convert Modules Simply

on:
  schedule:
    - cron: '0 0 * * *' # 每天执行一次
  workflow_dispatch: # 手动触发

jobs:
  update-snippet:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download links
      run: |
        mkdir -p Original
        while IFS= read -r line; do
          url=$(echo "$line" | awk '{print $1}')
          file=$(basename "$url")
          curl -L -o "Original/$file" "$url"
        done < Modules-Links.txt

    - name: Prepare Replacement Variables
      id: prepare-replacement
      run: |
        while IFS= read -r line; do
          url=$(echo "$line" | awk '{print $1}')
          author=$(echo "$line" | awk '{print $2}')
          filename=$(echo "$line" | awk '{print $3}')
          file="Original/$(basename "$url")"
          hostnames=$(grep -v '^#' "$file" | grep 'hostname = ' | awk -F'hostname = ' '{print $2}' | tr '\n' ', ' | sed 's/, $//')
          comment="# ${filename} // ${hostnames}"
          varname="${author}_${filename// /_}_COMMENT"
          echo "$varname=$comment" >> $GITHUB_ENV
        done < Modules-Links.txt

    - name: Convert snippets
      run: |
        mkdir -p Modules/Surge Modules/Loon
        while IFS= read -r line; do
          url=$(echo "$line" | awk '{print $1}')
          author=$(echo "$line" | awk '{print $2}')
          filename=$(echo "$line" | awk '{print $3}')
          base_filename=$(basename "$url" .plugin)
          bash Convert-Modules.sh "Original/$(basename "$url")" "${author}_${filename}" "${!author}_${filename// /_}_COMMENT"
        done < Modules-Links.txt

    - name: Create README in Modules directory
      run: |
        echo "# Modules for Surge and Loon" > Modules/README.md
        echo "" >> Modules/README.md
        echo "This directory contains converted modules from various sources, compatible with Surge and Loon." >> Modules/README.md
        echo "" >> Modules/README.md
        echo "## Sources" >> Modules/README.md
        echo "" >> Modules/README.md
        while IFS= read -r line; do
          url=$(echo "$line" | awk '{print $1}')
          author=$(echo "$line" | awk '{print $2}')
          filename=$(echo "$line" | awk '{print $3}')
          echo "- **${filename}**: Converted from [${filename} (${author})]($url)" >> Modules/README.md
        done < Modules-Links.txt

    - name: Commit and Push changes
      run: |
        git config --local user.name "ifflagged"
        git config --local user.email "qibo.sign@outlook.com"
        git add .
        if git diff --cached --quiet; then
          echo "No changes detected"
        else
          git commit -m "Update Modules"
          git push
        fi

    - name: Send TG Notification
      run: |
        if git rev-parse --verify HEAD^1 >/dev/null 2>&1; then
          UPDATED_FILES=$(git diff --name-only HEAD^1 HEAD Modules/)
        else
          UPDATED_FILES=$(git diff --name-only HEAD Modules/)
        fi
        
        if [ -n "$UPDATED_FILES" ]; then
          MESSAGE="The following files have been updated:\n$UPDATED_FILES"
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage -d chat_id=${{ secrets.TG_ID }} -d text="$MESSAGE"
        else
          echo "No files were updated, no notification sent."
        fi
