name: Convert Modules

on:
#  schedule:
#    - cron: '0 0 * * *' # 每天执行一次
  workflow_dispatch: # 手动触发

jobs:
  update-snippet:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download snippets
      run: |
        mkdir -p Original/ZenmoFeiShi Original/ddgksf2013 Original/RuCu6
        curl -L -o Original/ZenmoFeiShi/Pinduoduo.snippet https://github.com/ZenmoFeiShi/Qx/raw/main/Pinduoduo.snippet
        curl -L -o Original/ddgksf2013/SmzdmAds.conf https://github.com/ddgksf2013/Rewrite/raw/master/AdBlock/SmzdmAds.conf
        curl -L -o Original/ZenmoFeiShi/Didichuxing.snippet https://github.com/ZenmoFeiShi/Qx/raw/main/Didichuxing.snippet
        curl -L -o Original/RuCu6/Amap.snippet https://github.com/RuCu6/QuanX/raw/main/Rewrites/Cube/amap.snippet
        curl -L -o Original/RuCu6/Bilibili.snippet https://github.com/RuCu6/QuanX/raw/main/Rewrites/Cube/bilibili.snippet

    - name: Prepare Replacement Variables
      id: prepare-replacement
      run: |
        # 提取 hostname 并生成注释
        AMAP_HOSTNAMES=$(grep -oP '(?<=hostname = ).*' Original/RuCu6/Amap.snippet)
        AMAP_COMMENT="# 高德地图 // $AMAP_HOSTNAMES"
        echo "AMAP_COMMENT=$AMAP_COMMENT" >> $GITHUB_ENV

        BILIBILI_HOSTNAMES=$(grep -oP '(?<=hostname = ).*' Original/RuCu6/Bilibili.snippet)
        BILIBILI_COMMENT="# 哔哩哔哩 // $BILIBILI_HOSTNAMES"
        echo "BILIBILI_COMMENT=$BILIBILI_COMMENT" >> $GITHUB_ENV

        PDD_HOSTNAMES=$(grep -oP '(?<=hostname = ).*' Original/ZenmoFeiShi/Pinduoduo.snippet)
        PDD_COMMENT="# 拼多多 // $PDD_HOSTNAMES"
        echo "PDD_COMMENT=$PDD_COMMENT" >> $GITHUB_ENV

        SMZDM_HOSTNAMES=$(grep -oP '(?<=hostname = ).*' Original/ddgksf2013/SmzdmAds.conf)
        SMZDM_COMMENT="# 什么值得买 // $SMZDM_HOSTNAMES"
        echo "SMZDM_COMMENT=$SMZDM_COMMENT" >> $GITHUB_ENV

        DIDI_HOSTNAMES=$(grep -oP '(?<=hostname = ).*' Original/ZenmoFeiShi/Didichuxing.snippet)
        DIDI_COMMENT="# 滴滴出行 // $DIDI_HOSTNAMES"
        echo "DIDI_COMMENT=$DIDI_COMMENT" >> $GITHUB_ENV

    - name: Convert Amap.snippet to Surge sgmodule
      run: |
        mkdir -p Modules/Surge
        sed -e "1 i $AMAP_COMMENT" \
            -e 's/url reject-dict/- reject/Ig' \
            -e "s/url reject-200/- reject/Ig" \
            -e 's/url reject/- reject/Ig' \
            -e '/url script-response-body/ s/^/Amap = type=http-response,pattern=/' \
            -e '/url script-response-header/ s/^/Amap = type=http-response,pattern=/' \
            -e '/url script-request-body/ s/^/Amap = type=http-request,pattern=/' \
            -e 's/ url script-response-body /,requires-body=1,script-path=/Ig' \
            -e 's/ url script-response-header /,requires-body=0,script-path=/Ig' \
            -e 's/ url script-request-body /,requires-body=1,script-path=/Ig' \
            -e 's/raw.githubusercontent.com/github.com/Ig' \
            -e 's/\/main\//\/raw\/main\//Ig' \
            -e 's/\/master\//\/raw\/master\//Ig' \
            -e 's/hostname =/hostname = %APPEND%/Ig' \
            Original/RuCu6/Amap.snippet > Modules/Surge/Amap.sgmodule

    - name: Convert Amap.snippet to Loon plugin
      run: |
        mkdir -p Modules/Loon
        sed -e "1 i $AMAP_COMMENT" \
            -e 's/url reject-dict/reject-dict/Ig' \
            -e "s/url reject-200/reject-200/Ig" \
            -e 's/url reject/reject/Ig' \
            -e '/url script-response-body/ s/^/http-response /' \
            -e '/url script-response-header/ s/^/http-response /' \
            -e '/url script-request-body/ s/^/http-request /' \
            -e '/-body/ s/$/, requires-body = true, tag = Amap/' \
            -e '/-header/ s/$/, requires-body = false, tag = Amap/' \
            -e 's/url script-response-body/script-path=/Ig' \
            -e 's/url script-request-body/script-path=/Ig' \
            -e 's/url script-request-header/script-path=/Ig' \
            -e 's/raw.githubusercontent.com/github.com/Ig' \
            -e 's/\/main\//\/raw\/main\//Ig' \
            -e 's/\/master\//\/raw\/master\//Ig' \
            Original/RuCu6/Amap.snippet > Modules/Loon/Amap.plugin

    - name: Convert Bilibili.snippet to Surge sgmodule
      run: |
        sed -e "1 i $BILIBILI_COMMENT" \
            -e 's/url reject-dict/- reject/Ig' \
            -e "s/url reject-200/- reject/Ig" \
            -e 's/url reject/- reject/Ig' \
            -e '/url script-response-body/ s/^/Bilibili = type=http-response,pattern=/' \
            -e '/url script-response-header/ s/^/Bilibili = type=http-response,pattern=/' \
            -e '/url script-request-body/ s/^/Bilibili = type=http-request,pattern=/' \
            -e 's/ url script-response-body /,requires-body=1,script-path=/Ig' \
            -e 's/ url script-response-header /,requires-body=0,script-path=/Ig' \
            -e 's/ url script-request-body /,requires-body=1,script-path=/Ig' \
            -e 's/raw.githubusercontent.com/github.com/Ig' \
            -e 's/\/main\//\/raw\/main\//Ig' \
            -e 's/\/master\//\/raw\/master\//Ig' \
            -e 's/hostname =/hostname = %APPEND%/Ig' \
            Original/RuCu6/Bilibili.snippet > Modules/Surge/Bilibili.sgmodule

    - name: Convert Bilibili.snippet to Loon plugin
      run: |
        sed -e "1 i $BILIBILI_COMMENT" \
            -e 's/url reject-dict/reject-dict/Ig' \
            -e "s/url reject-200/reject-200/Ig" \
            -e 's/url reject/reject/Ig' \
            -e '/url script-response-body/ s/^/http-response /' \
            -e '/url script-response-header/ s/^/http-response /' \
            -e '/url script-request-body/ s/^/http-request /' \
            -e '/-body/ s/$/, requires-body = true, tag = Bilibili/' \
            -e '/-header/ s/$/, requires-body = false, tag = Bilibili/' \
            -e 's/url script-response-body/script-path=/Ig' \
            -e 's/url script-response-header/script-path=/Ig' \
            -e 's/url script-request-body/script-path=/Ig' \
            -e 's/raw.githubusercontent.com/github.com/Ig' \
            -e 's/\/main\//\/raw\/main\//Ig' \
            -e 's/\/master\//\/raw\/master\//Ig' \
            Original/RuCu6/Bilibili.snippet > Modules/Loon/Bilibili.plugin

    - name: Convert Didichuxing.snippet to Surge sgmodule
      run: |
        sed -e "1 i $DIDI_COMMENT" \
            -e 's/url reject-dict/- reject/Ig' \
            -e "s/url reject-200/- reject/Ig" \
            -e 's/url reject/- reject/Ig' \
            -e '/url script-response-body/ s/^/DIDI = type=http-response,pattern=/' \
            -e '/url script-response-header/ s/^/DIDI = type=http-response,pattern=/' \
            -e '/url script-request-body/ s/^/DIDI = type=http-request,pattern=/' \
            -e 's/ url script-response-body /,requires-body=1,script-path=/Ig' \
            -e 's/ url script-response-header /,requires-body=0,script-path=/Ig' \
            -e 's/ url script-request-body /,requires-body=1,script-path=/Ig' \
            -e 's/raw.githubusercontent.com/github.com/Ig' \
            -e 's/\/main\//\/raw\/main\//Ig' \
            -e 's/\/master\//\/raw\/master\//Ig' \
            -e 's/IP-CIDR/IP-CIDR/Ig' \
            -e 's/, REJECT/, REJECT, no-resolve/Ig' \
            -e 's/hostname =/hostname = %APPEND%/Ig' \
            Original/ZenmoFeiShi/Didichuxing.snippet > Modules/Surge/Didichuxing.sgmodule

    - name: Convert Didichuxing.snippet to Loon plugin
      run: |
        sed -e "1 i $DIDI_COMMENT" \
            -e 's/url reject-dict/reject-dict/Ig' \
            -e "s/url reject-200/reject-200/Ig" \
            -e 's/url reject/reject/Ig' \
            -e '/url script-response-body/ s/^/http-response /' \
            -e '/url script-response-header/ s/^/http-response /' \
            -e '/url script-request-body/ s/^/http-request /' \
            -e '/-body/ s/$/, requires-body = true, tag = DIDI/' \
            -e '/-header/ s/$/, requires-body = false, tag = DIDI/' \
            -e 's/url script-response-body/script-path=/Ig' \
            -e 's/url script-response-header/script-path=/Ig' \
            -e 's/url script-request-body/script-path=/Ig' \
            -e 's/raw.githubusercontent.com/github.com/Ig' \
            -e 's/\/main\//\/raw\/main\//Ig' \
            -e 's/\/master\//\/raw\/master\//Ig' \
            -e 's/IP-CIDR/IP-CIDR/Ig' \
            -e 's/, REJECT/, REJECT, no-resolve/Ig' \
            Original/ZenmoFeiShi/Didichuxing.snippet > Modules/Loon/Didichuxing.plugin

    - name: Convert Pinduoduo.snippet to Surge sgmodule
      run: |
        sed -e "1 i $PDD_COMMENT" \
            -e 's/url reject-dict/- reject/Ig' \
            -e "s/url reject-200/- reject/Ig" \
            -e 's/url reject/- reject/Ig' \
            -e '/url script-response-body/ s/^/Pinduoduo = type=http-response,pattern=/' \
            -e '/url script-response-header/ s/^/Pinduoduo = type=http-response,pattern=/' \
            -e '/url script-request-body/ s/^/Pinduoduo = type=http-request,pattern=/' \
            -e 's/ url script-response-body /,requires-body=1,script-path=/Ig' \
            -e 's/ url script-response-header /,requires-body=0,script-path=/Ig' \
            -e 's/ url script-request-body /,requires-body=1,script-path=/Ig' \
            -e 's/raw.githubusercontent.com/github.com/Ig' \
            -e 's/\/main\//\/raw\/main\//Ig' \
            -e 's/\/master\//\/raw\/master\//Ig' \
            -e 's/hostname =/hostname = %APPEND%/Ig' \
            Original/ZenmoFeiShi/Pinduoduo.snippet > Modules/Surge/Pinduoduo.sgmodule

    - name: Convert Pinduoduo.snippet to Loon plugin
      run: |
        sed -e "1 i $PDD_COMMENT" \
            -e 's/url reject-dict/reject-dict/Ig' \
            -e "s/url reject-200/reject-200/Ig" \
            -e 's/url reject/reject/Ig' \
            -e '/url script-response-body/ s/^/http-response /' \
            -e '/url script-response-header/ s/^/http-response /' \
            -e '/url script-request-body/ s/^/http-request /' \
            -e '/-body/ s/$/, requires-body = true, tag = Pinduoduo/' \
            -e '/-header/ s/$/, requires-body = false, tag = Pinduoduo/' \
            -e 's/url script-response-body/script-path=/Ig' \
            -e 's/url script-response-header/script-path=/Ig' \
            -e 's/url script-request-body/script-path=/Ig' \
            -e 's/raw.githubusercontent.com/github.com/Ig' \
            -e 's/\/main\//\/raw\/main\//Ig' \
            -e 's/\/master\//\/raw\/master\//Ig' \
            Original/ZenmoFeiShi/Pinduoduo.snippet > Modules/Loon/Pinduoduo.plugin

    - name: Convert SmzdmAds.conf to Surge sgmodule
      run: |
        sed -e "1 i $SMZDM_COMMENT" \
            -e 's/url reject-dict/- reject/Ig' \
            -e "s/url reject-200/- reject/Ig" \
            -e 's/url reject/- reject/Ig' \
            -e '/url script-response-body/ s/^/Smzdm = type=http-response,pattern=/' \
            -e '/url script-response-header/ s/^/Smzdm = type=http-response,pattern=/' \
            -e '/url script-request-body/ s/^/Smzdm = type=http-request,pattern=/' \
            -e 's/ url script-response-body /,requires-body=1,script-path=/Ig' \
            -e 's/ url script-response-header /,requires-body=0,script-path=/Ig' \
            -e 's/ url script-request-body /,requires-body=1,script-path=/Ig' \
            -e 's/raw.githubusercontent.com/github.com/Ig' \
            -e 's/\/main\//\/raw\/main\//Ig' \
            -e 's/\/master\//\/raw\/master\//Ig' \
            -e 's/hostname =/hostname = %APPEND%/Ig' \
            Original/ddgksf2013/SmzdmAds.conf > Modules/Surge/SmzdmAds.sgmodule

    - name: Convert SmzdmAds.conf to Loon plugin
      run: |
        sed -e "1 i $SMZDM_COMMENT" \
            -e 's/url reject-dict/reject-dict/Ig' \
            -e "s/url reject-200/reject-200/Ig" \
            -e 's/url reject/reject/Ig' \
            -e '/url script-response-body/ s/^/http-response /' \
            -e '/url script-response-header/ s/^/http-response /' \
            -e '/url script-request-body/ s/^/http-request /' \
            -e '/-body/ s/$/, requires-body = true, tag = SmzdmAds/' \
            -e '/-header/ s/$/, requires-body = false, tag = SmzdmAds/' \
            -e 's/url script-response-body/script-path=/Ig' \
            -e 's/url script-response-header/script-path=/Ig' \
            -e 's/url script-request-body/script-path=/Ig' \
            -e 's/raw.githubusercontent.com/github.com/Ig' \
            -e 's/\/main\//\/raw\/main\//Ig' \
            -e 's/\/master\//\/raw\/master\//Ig' \
            Original/ddgksf2013/SmzdmAds.conf > Modules/Loon/SmzdmAds.plugin

    - name: Create README in Modules directory
      run: |
        echo "# Modules for Surge and Loon" > Modules/README.md
        echo "" >> Modules/README.md
        echo "This repository contains Surge and Loon configurations." >> Modules/README.md
        echo "" >> Modules/README.md
        echo "## Source" >> Modules/README.md
        echo "" >> Modules/README.md
        
        echo "Amap snippet is sourced from:" >> Modules/README.md
        echo "[RuCu6/QuanX](https://github.com/RuCu6/QuanX/raw/main/Rewrites/Cube/amap.snippet)" >> Modules/README.md
        echo "" >> Modules/README.md
        
        echo "Bilibili snippet is sourced from:" >> Modules/README.md
        echo "[RuCu6/QuanX](https://github.com/RuCu6/QuanX/raw/main/Rewrites/Cube/bilibili.snippet)" >> Modules/README.md
        echo "" >> Modules/README.md
        
        echo "Didichuxing snippet is sourced from:" >> Modules/README.md
        echo "[ZenmoFeiShi/Qx](https://github.com/ZenmoFeiShi/Qx/raw/main/Didichuxing.snippet)" >> Modules/README.md
        echo "" >> Modules/README.md
        
        echo "Pinduoduo snippet is sourced from:" >> Modules/README.md
        echo "[ZenmoFeiShi/Qx](https://github.com/ZenmoFeiShi/Qx/raw/main/Pinduoduo.snippet)" >> Modules/README.md
        echo "" >> Modules/README.md
        
        echo "SmzdmAds snippet is sourced from:" >> Modules/README.md
        echo "[ddgksf2013/Rewrite](https://github.com/ddgksf2013/Rewrite/raw/master/AdBlock/SmzdmAds.conf)" >> Modules/README.md

    - name: Check if files are updated
      run: |
        git config --local user.name "ifflagged"
        git config --local user.email "qibo.sign@outlook.com"
        git add .
        if ! git diff --cached --exit-code; then
          git commit -m 'Update Surge and Loon modules'
          git push
        fi

    - name: Send TG notification
      if: success()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TG_ID }}
        token: ${{ secrets.TG_BOT_TOKEN }}
        message: 'Surge and Loon modules have been updated.'
