name: Convert Modules

on:
  schedule:
    - cron: '0 0 * * *' # 每天执行一次
  workflow_dispatch: # 手动触发

jobs:
  update-snippet:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download snippets
      run: |
        mkdir -p Original/ZenmoFeiShi Original/ddgksf2013 Original/RuCu6
        curl -L -o Original/RuCu6/Amap.snippet https://github.com/RuCu6/QuanX/raw/main/Rewrites/Cube/amap.snippet
        curl -L -o Original/RuCu6/Bilibili.snippet https://github.com/RuCu6/QuanX/raw/main/Rewrites/Cube/bilibili.snippet
        curl -L -o Original/ZenmoFeiShi/Didichuxing.snippet https://github.com/ZenmoFeiShi/Qx/raw/main/Didichuxing.snippet
        curl -L -o Original/ZenmoFeiShi/Pinduoduo.snippet https://github.com/ZenmoFeiShi/Qx/raw/main/Pinduoduo.snippet
        curl -L -o Original/ddgksf2013/SmzdmAds.conf https://github.com/ddgksf2013/Rewrite/raw/master/AdBlock/SmzdmAds.conf

    - name: Prepare Replacement Variables
      id: prepare-replacement
      run: |
        # 提取各 snippet 中的 hostname
        AMAP_HOSTNAMES=$(grep -oP '(?<=hostname = ).*' Original/RuCu6/Amap.snippet)
        BILIBILI_HOSTNAMES=$(grep -oP '(?<=hostname = ).*' Original/RuCu6/Bilibili.snippet)
        DIDI_HOSTNAMES=$(grep -oP '(?<=hostname = ).*' Original/ZenmoFeiShi/Didichuxing.snippet)
        PDD_HOSTNAMES=$(grep -oP '(?<=hostname = ).*' Original/ZenmoFeiShi/Pinduoduo.snippet)
        SMZDM_HOSTNAMES=$(grep -oP '(?<=hostname = ).*' Original/ddgksf2013/SmzdmAds.conf)
        
        # 生成注释行
        AMAP_COMMENT="# Amap // $AMAP_HOSTNAMES"
        BILIBILI_COMMENT="# Bilibili // $BILIBILI_HOSTNAMES"
        DIDI_COMMENT="# 滴滴出行 // $DIDI_HOSTNAMES"
        PDD_COMMENT="# 拼多多 // $PDD_HOSTNAMES"
        SMZDM_COMMENT="# 什么值得买 // $SMZDM_HOSTNAMES"
        
        # 导出为环境变量
        echo "AMAP_COMMENT=$AMAP_COMMENT" >> $GITHUB_ENV
        echo "BILIBILI_COMMENT=$BILIBILI_COMMENT" >> $GITHUB_ENV
        echo "DIDI_COMMENT=$DIDI_COMMENT" >> $GITHUB_ENV
        echo "PDD_COMMENT=$PDD_COMMENT" >> $GITHUB_ENV
        echo "SMZDM_COMMENT=$SMZDM_COMMENT" >> $GITHUB_ENV

    - name: Convert Amap.snippet to Surge sgmodule
      run: |
        mkdir -p Modules/Surge
        sed -e "1 i $AMAP_COMMENT" \
            -e 's/url reject-dict/reject-dict/Ig' \
            -e "s/url reject-200/- reject/Ig" \
            -e 's/url reject/- reject/Ig' \
            -e '/url script-response-body/ s/^/Amap = type=http-response,pattern=/' \
            -e '/url script-request-body/ s/^/Amap = type=http-request,pattern=/' \
            -e 's/ url script-response-body /,requires-body=1,script-path=/Ig' \
            -e 's/ url script-request-body /,requires-body=1,script-path=/Ig' \
            -e 's/raw.githubusercontent.com/github.com/Ig' \
            -e 's/\/main\//\/raw\/main\//Ig' \
            -e 's/\/master\//\/raw\/master\//Ig' \
            -e 's/hostname =/hostname = %APPEND%/Ig' \
            Original/RuCu6/Amap.snippet > Modules/Surge/Amap.sgmodule

    - name: Convert Amap.snippet to Loon plugin
      run: |
        mkdir -p Modules/Loon
        sed -e "1 i $AMAP_COMMENT" \
            -e 's/url reject-dict/reject-dict/Ig' \
            -e "s/url reject-200/- reject/Ig" \
            -e 's/url reject/- reject/Ig' \
            -e '/url script-response-body/ s/^/http-response /' \
            -e '/url script-request-body/ s/^/http-request /' \
            -e 's/url script-response-body/script-path=/Ig' \
            -e 's/url script-request-body/script-path=/Ig' \
            -e '/script-path=/ s/$/, requires-body = true, tag = Amap/' \
            -e 's/raw.githubusercontent.com/github.com/Ig' \
            -e 's/\/main\//\/raw\/main\//Ig' \
            -e 's/\/master\//\/raw\/master\//Ig' \
            Original/RuCu6/Amap.snippet > Modules/Loon/Amap.plugin

    - name: Convert Bilibili.snippet to Surge sgmodule
      run: |
        sed -e "1 i $BILIBILI_COMMENT" \
            -e 's/url reject-dict/reject-dict/Ig' \
            -e "s/url reject-200/- reject/Ig" \
            -e 's/url reject/- reject/Ig' \
            -e '/url script-response-body/ s/^/Bilibili = type=http-response,pattern=/' \
            -e '/url script-request-body/ s/^/Bilibili = type=http-request,pattern=/' \
            -e 's/ url script-response-body /,requires-body=1,script-path=/Ig' \
            -e 's/ url script-request-body /,requires-body=1,script-path=/Ig' \
            -e 's/raw.githubusercontent.com/github.com/Ig' \
            -e 's/\/main\//\/raw\/main\//Ig' \
            -e 's/\/master\//\/raw\/master\//Ig' \
            -e 's/hostname =/hostname = %APPEND%/Ig' \
            Original/RuCu6/Bilibili.snippet > Modules/Surge/Bilibili.sgmodule

    - name: Convert Bilibili.snippet to Loon plugin
      run: |
        sed -e "1 i $BILIBILI_COMMENT" \
            -e 's/url reject-dict/reject-dict/Ig' \
            -e "s/url reject-200/- reject/Ig" \
            -e 's/url reject/- reject/Ig' \
            -e '/url script-response-body/ s/^/http-response /' \
            -e '/url script-request-body/ s/^/http-request /' \
            -e 's/url script-response-body/script-path=/Ig' \
            -e 's/url script-request-body/script-path=/Ig' \
            -e '/script-path=/ s/$/, requires-body = true, tag = Bilibili/' \
            -e 's/raw.githubusercontent.com/github.com/Ig' \
            -e 's/\/main\//\/raw\/main\//Ig' \
            -e 's/\/master\//\/raw\/master\//Ig' \
            Original/RuCu6/Bilibili.snippet > Modules/Loon/Bilibili.plugin

    - name: Convert Didichuxing.snippet to Surge sgmodule
      run: |
        sed -e "1 i $DIDI_COMMENT" \
            -e 's/url reject-dict/reject-dict/Ig' \
            -e "s/url reject-200/- reject/Ig" \
            -e 's/url reject/- reject/Ig' \
            -e '/url script-response-body/ s/^/DIDI = type=http-response,pattern=/' \
            -e '/url script-request-body/ s/^/DIDI = type=http-request,pattern=/' \
            -e 's/ url script-response-body /,requires-body=1,script-path=/Ig' \
            -e 's/ url script-request-body /,requires-body=1,script-path=/Ig' \
            -e 's/raw.githubusercontent.com/github.com/Ig' \
            -e 's/\/main\//\/raw\/main\//Ig' \
            -e 's/\/master\//\/raw\/master\//Ig' \
            -e 's/IP-CIDR/IP-CIDR/Ig' \
            -e 's/, REJECT/, REJECT, no-resolve/Ig' \
            -e 's/hostname =/hostname = %APPEND%/Ig' \
            Original/ZenmoFeiShi/Didichuxing.snippet > Modules/Surge/Didichuxing.sgmodule

    - name: Convert Didichuxing.snippet to Loon plugin
      run: |
        sed -e "1 i $DIDI_COMMENT" \
            -e 's/url reject-dict/reject-dict/Ig' \
            -e "s/url reject-200/- reject/Ig" \
            -e 's/url reject/- reject/Ig' \
            -e '/url script-response-body/ s/^/http-response /' \
            -e '/url script-request-body/ s/^/http-request /' \
            -e 's/url script-response-body/script-path=/Ig' \
            -e 's/url script-request-body/script-path=/Ig' \
            -e '/script-path=/ s/$/, requires-body = true, tag = Didichuxing/' \
            -e 's/raw.githubusercontent.com/github.com/Ig' \
            -e 's/\/main\//\/raw\/main\//Ig' \
            -e 's/\/master\//\/raw\/master\//Ig' \
            Original/ZenmoFeiShi/Didichuxing.snippet > Modules/Loon/Didichuxing.plugin

    - name: Convert Pinduoduo.snippet to Surge sgmodule
      run: |
        sed -e "1 i $PDD_COMMENT" \
            -e 's/url reject-dict/reject-dict/Ig' \
            -e "s/url reject-200/- reject/Ig" \
            -e 's/url reject/- reject/Ig' \
            -e '/url script-response-body/ s/^/PDD = type=http-response,pattern=/' \
            -e '/url script-request-body/ s/^/PDD = type=http-request,pattern=/' \
            -e 's/ url script-response-body /,requires-body=1,script-path=/Ig' \
            -e 's/ url script-request-body /,requires-body=1,script-path=/Ig' \
            -e 's/raw.githubusercontent.com/github.com/Ig' \
            -e 's/\/main\//\/raw\/main\//Ig' \
            -e 's/\/master\//\/raw\/master\//Ig' \
            -e 's/IP-CIDR/IP-CIDR/Ig' \
            -e 's/, REJECT/, REJECT, no-resolve/Ig' \
            -e 's/hostname =/hostname = %APPEND%/Ig' \
            Original/ZenmoFeiShi/Pinduoduo.snippet > Modules/Surge/Pinduoduo.sgmodule

    - name: Convert Pinduoduo.snippet to Loon plugin
      run: |
        sed -e "1 i $PDD_COMMENT" \
            -e 's/url reject-dict/reject-dict/Ig' \
            -e "s/url reject-200/- reject/Ig" \
            -e 's/url reject/- reject/Ig' \
            -e '/url script-response-body/ s/^/http-response /' \
            -e '/url script-request-body/ s/^/http-request /' \
            -e 's/url script-response-body/script-path=/Ig' \
            -e 's/url script-request-body/script-path=/Ig' \
            -e '/script-path=/ s/$/, requires-body = true, tag = Pinduoduo/' \
            -e 's/raw.githubusercontent.com/github.com/Ig' \
            -e 's/\/main\//\/raw\/main\//Ig' \
            -e 's/\/master\//\/raw\/master\//Ig' \
            Original/ZenmoFeiShi/Pinduoduo.snippet > Modules/Loon/Pinduoduo.plugin

    - name: Convert SmzdmAds.conf to Surge sgmodule
      run: |
        sed -e "1 i $SMZDM_COMMENT" \
            -e 's/^hostname =/hostname = %APPEND%/Ig' \
            -e 's/url reject-dict/reject-dict/Ig' \
            -e "s/url reject-200/- reject/Ig" \
            -e 's/url reject/- reject/Ig' \
            -e '/url script-response-body/ s/^/SMZDM = type=http-response,pattern=/' \
            -e '/url script-request-body/ s/^/SMZDM = type=http-request,pattern=/' \
            -e 's/ url script-response-body /,requires-body=1,script-path=/Ig' \
            -e 's/ url script-request-body /,requires-body=1,script-path=/Ig' \
            -e 's/raw.githubusercontent.com/github.com/Ig' \
            -e 's/\/main\//\/raw\/main\//Ig' \
            -e 's/\/master\//\/raw\/master\//Ig' \
            Original/ddgksf2013/SmzdmAds.conf > Modules/Surge/SmzdmAds.sgmodule

    - name: Convert SmzdmAds.conf to Loon plugin
      run: |
        sed -e "1 i $SMZDM_COMMENT" \
            -e 's/^hostname =/hostname = %APPEND%/Ig' \
            -e 's/url reject-dict/reject-dict/Ig' \
            -e "s/url reject-200/- reject/Ig" \
            -e 's/url reject/- reject/Ig' \
            -e '/url script-response-body/ s/^/http-response /' \
            -e '/url script-request-body/ s/^/http-request /' \
            -e 's/url script-response-body/script-path=/Ig' \
            -e 's/url script-request-body/script-path=/Ig' \
            -e '/script-path=/ s/$/, requires-body = true, tag = SmzdmAds/' \
            -e 's/raw.githubusercontent.com/github.com/Ig' \
            -e 's/\/main\//\/raw\/main\//Ig' \
            -e 's/\/master\//\/raw\/master\//Ig' \
            Original/ddgksf2013/SmzdmAds.conf > Modules/Loon/SmzdmAds.plugin

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add Modules/*
        git commit -m "Updated Surge and Loon modules on $(date +"%Y-%m-%d")" || echo "No changes to commit"
        git push || echo "No changes to push"

    - name: Send Telegram Notification
      if: success() && steps.commit-changes.outputs.COMMIT_OUTPUT != 'No changes to commit'
      uses: appleboy/telegram-action@0.6.0
      with:
        to: ${{ secrets.TG_ID }}
        token: ${{ secrets.TG_BOT_TOKEN }}
        message: "Surge and Loon modules have been updated."
