name: Convert Modules

on:
  schedule:
    - cron: '0 0 * * *' # 每天执行一次
  workflow_dispatch: # 手动触发

jobs:
  update-snippet:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download Pinduoduo.snippet and SmzdmAds.conf
      run: |
        mkdir -p Original/ZenmoFeiShi Original/ddgksf2013
        curl -L -o Original/ZenmoFeiShi/Pinduoduo.snippet https://github.com/ZenmoFeiShi/Qx/raw/main/Pinduoduo.snippet
        curl -L -o Original/ddgksf2013/SmzdmAds.conf https://github.com/ddgksf2013/Rewrite/raw/master/AdBlock/SmzdmAds.conf

    - name: Prepare Replacement Variables
      id: prepare-replacement
      run: |
        # 提取 Pinduoduo.snippet 中的 hostname
        PDD_HOSTNAMES=$(grep -oP '(?<=hostname = ).*' Original/ZenmoFeiShi/Pinduoduo.snippet)
        
        # 生成拼多多注释行
        PDD_COMMENT="# 拼多多 // $PDD_HOSTNAMES"
        
        # 将 PDD_COMMENT 变量导出为环境变量
        echo "PDD_COMMENT=$PDD_COMMENT" >> $GITHUB_ENV

        # 提取 SmzdmAds.conf 中的 hostname
        SMZDM_HOSTNAMES=$(grep -oP '(?<=hostname = ).*' Original/ddgksf2013/SmzdmAds.conf)

        # 生成 SMZDM 注释行
        SMZDM_COMMENT="# 什么值得买 // $SMZDM_HOSTNAMES"
        
        # 将 SMZDM_COMMENT 变量导出为环境变量
        echo "SMZDM_COMMENT=$SMZDM_COMMENT" >> $GITHUB_ENV

    - name: Convert Pinduoduo.snippet to Surge sgmodule
      run: |
        # 创建 Modules/Surge 文件夹
        mkdir -p Modules/Surge
        
        # 修改并生成适用于 Surge 的 Pinduoduo.sgmodule 文件
        sed -e "1 i $PDD_COMMENT" \
            -e 's/url reject-dict/reject-dict/Ig' \
            -e "s/url reject-200/- reject/Ig" \
            -e 's/url reject/- reject/Ig' \
            -e '/url script-response-body/ s/^/Pinduoduo = type=http-response,pattern=/' \
            -e '/url script-request-body/ s/^/Pinduoduo = type=http-request,pattern=/' \
            -e 's/ url script-response-body /,requires-body=1,script-path=/Ig' \
            -e 's/ url script-request-body /,requires-body=1,script-path=/Ig' \
            -e 's/raw.githubusercontent.com/github.com/Ig' \
            -e 's/\/main\//\/raw\/main\//Ig' \
            -e 's/\/master\//\/raw\/master\//Ig' \
            -e 's/hostname =/hostname = %APPEND%/Ig' \
            Original/ZenmoFeiShi/Pinduoduo.snippet > Modules/Surge/Pinduoduo.sgmodule

    - name: Convert Pinduoduo.snippet to Loon plugin
      run: |
        # 创建 Modules/Loon 文件夹
        mkdir -p Modules/Loon
        
        # 修改并生成适用于 Loon 的 Pinduoduo.plugin 文件
        sed -e "1 i $PDD_COMMENT" \
            -e 's/url reject-dict/reject-dict/Ig' \
            -e "s/url reject-200/- reject/Ig" \
            -e 's/url reject/- reject/Ig' \
            -e '/url script-response-body/ s/^/http-response /' \
            -e '/url script-request-body/ s/^/http-request /' \
            -e 's/url script-response-body/script-path=/Ig' \
            -e 's/url script-request-body/script-path=/Ig' \
            -e '/script-path=/ s/$/, requires-body = true, tag = Pinduoduo/' \
            -e 's/raw.githubusercontent.com/github.com/Ig' \
            -e 's/\/main\//\/raw\/main\//Ig' \
            -e 's/\/master\//\/raw\/master\//Ig' \
            Original/ZenmoFeiShi/Pinduoduo.snippet > Modules/Loon/Pinduoduo.plugin

    - name: Convert SmzdmAds.conf to Surge sgmodule
      run: |
        # 修改并生成适用于 Surge 的 SmzdmAds.sgmodule 文件
        sed -e "1 i $SMZDM_COMMENT" \
            -e 's/url reject-dict/reject-dict/Ig' \
            -e "s/url reject-200/- reject/Ig" \
            -e 's/url reject/- reject/Ig' \
            -e '/url script-response-body/ s/^/SMZDM = type=http-response,pattern=/' \
            -e '/url script-request-body/ s/^/SMZDM = type=http-request,pattern=/' \
            -e 's/ url script-response-body /,requires-body=1,script-path=/Ig' \
            -e 's/ url script-request-body /,requires-body=1,script-path=/Ig' \
            -e 's/raw.githubusercontent.com/github.com/Ig' \
            -e 's/\/main\//\/raw\/main\//Ig' \
            -e 's/\/master\//\/raw\/master\//Ig' \
            -e 's/hostname =/hostname = %APPEND%/Ig' \
            Original/ddgksf2013/SmzdmAds.conf > Modules/Surge/SmzdmAds.sgmodule

    - name: Convert SmzdmAds.conf to Loon plugin
      run: |
        # 修改并生成适用于 Loon 的 SmzdmAds.plugin 文件
        sed -e "1 i $SMZDM_COMMENT" \
            -e 's/url reject-dict/reject-dict/Ig' \
            -e "s/url reject-200/- reject/Ig" \
            -e 's/url reject/- reject/Ig' \
            -e '/url script-response-body/ s/^/http-response /' \
            -e '/url script-request-body/ s/^/http-request /' \
            -e 's/url script-response-body/script-path=/Ig' \
            -e 's/url script-request-body/script-path=/Ig' \
            -e '/script-path=/ s/$/, requires-body = true, tag = SMZDM/' \
            -e 's/raw.githubusercontent.com/github.com/Ig' \
            -e 's/\/main\//\/raw\/main\//Ig' \
            -e 's/\/master\//\/raw\/master\//Ig' \
            Original/ddgksf2013/SmzdmAds.conf > Modules/Loon/SmzdmAds.plugin

    - name: Create README in Modules directory
      run: |
        echo "# Modules for Surge and Loon" > Modules/README.md
        echo "" >> Modules/README.md
        echo "This repository contains Surge and Loon configurations." >> Modules/README.md
        echo "" >> Modules/README.md
        echo "## Source" >> Modules/README.md
        echo "Pinduoduo snippet is sourced from: [ZenmoFeiShi/Qx](https://github.com/ZenmoFeiShi/Qx/raw/main/Pinduoduo.snippet)" >> Modules/README.md
        echo "SmzdmAds snippet is sourced from: [ddgksf2013/Rewrite](https://github.com/ddgksf2013/Rewrite/raw/master/AdBlock/SmzdmAds.conf)" >> Modules/README.md

    - name: Commit changes
      run: |
        git config --local user.name "ifflagged"
        git config --local user.email "qibo.sign@outlook.com"
        git add .
        git commit -m "Convert Pinduoduo.snippet and SmzdmAds.conf for Surge and Loon"
        git push
