name: Convert Modules

on:
  schedule:
    - cron: '0 0 * * *' # 每天执行一次
  workflow_dispatch: # 手动触发

jobs:
  update-snippet:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download snippets and prepare variables
      run: |
        mkdir -p Original
        README_CONTENT=""
        FILES_LIST=""
        while read -r url; do
          # 提取作者名称和文件名
          author=$(echo "$url" | awk -F'/' '{print $4}')
          filename=$(basename "$url")
          filename_no_ext=$(basename "$url" | cut -d'.' -f1)
          # 创建作者文件夹
          mkdir -p "Original/$author"
          # 下载文件
          file_path="Original/$author/$filename"
          curl -L -o "$file_path" "$url"
          
          # 准备README内容
          README_CONTENT="${README_CONTENT}\n- **${filename_no_ext}**: Converted from [${author} ${filename_no_ext}](${url})"
          
          # 提取非注释行中的 hostname 信息
          hostnames=$(grep -v '^#' "$file_path" | grep 'hostname = ' | awk -F'hostname = ' '{print $2}' | tr '\n' ', ' | sed 's/, $//')
          # 生成注释内容
          comment="# ${filename_no_ext} // ${hostnames}"
          
          # 将文件信息追加到 FILES_LIST
          FILES_LIST="${FILES_LIST}\n${file_path};${author};${filename_no_ext};${comment}"
        done < Modules-Links.txt
        
        # 将 README 内容和文件列表保存到环境变量
        echo "README_CONTENT=$(echo -e "$README_CONTENT")" >> $GITHUB_ENV
        echo "FILES_LIST=$(echo -e "$FILES_LIST")" >> $GITHUB_ENV

    - name: Convert snippets
      run: |
        IFS=$'\n'
        for file_info in $FILES_LIST; do
          # 跳过空行
          [ -z "$file_info" ] && continue
          file_path=$(echo $file_info | cut -d';' -f1)
          author=$(echo $file_info | cut -d';' -f2)
          filename=$(echo $file_info | cut -d';' -f3)
          comment=$(echo $file_info | cut -d';' -f4)
          bash Convert-Modules.sh "$file_path" "${author}_${filename}" "$comment"
        done

    - name: Create README in Modules directory
      run: |
        echo "# Modules for Surge and Loon" > Modules/README.md
        echo "" >> Modules/README.md
        echo "This directory contains converted modules from various sources, compatible with Surge and Loon." >> Modules/README.md
        echo "" >> Modules/README.md
        echo "## Sources" >> Modules/README.md
        echo "" >> Modules/README.md
        echo -e "$README_CONTENT" >> Modules/README.md

    - name: Commit and Push changes
      run: |
        git config --local user.name "ifflagged"
        git config --local user.email "qibo.sign@outlook.com"
        git add .
        if git diff --cached --quiet; then
          echo "No changes detected"
        else
          git commit -m "Update Modules"
          git push
        fi
        
    - name: Send TG Notification
      run: |
        # Check if there is a previous commit
        if git rev-parse --verify HEAD^1 >/dev/null 2>&1; then
          UPDATED_FILES=$(git diff --name-only HEAD^1 HEAD Modules/)
        else
          UPDATED_FILES=$(git diff --name-only HEAD Modules/)
        fi
    
        if [ -n "$UPDATED_FILES" ]; then
          MESSAGE=$(echo -e "The following files have been updated:\n$UPDATED_FILES")
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage -d chat_id=${{ secrets.TG_ID }} -d text="$MESSAGE"
        else
          echo "No files were updated, no notification sent."
        fi
