- name: Download snippets and prepare variables
  id: download-and-prepare
  run: |
    mkdir -p Original
    README_CONTENT=""
    FILES_LIST=""
    declare -A file_count
    while read -r url; do
      # 跳过空行和注释行
      [[ -z "$url" || "$url" =~ ^# ]] && continue

      # 提取作者名称和文件名
      author=$(echo "$url" | awk -F'/' '{print $4}')
      filename=$(basename "$url")
      filename_no_ext=$(basename "$url" | cut -d'.' -f1)

      # 处理文件重命名
      if [[ -n "${file_count[$author:$filename_no_ext]}" ]]; then
        count=${file_count[$author:$filename_no_ext]}
        filename_no_ext="${filename_no_ext}-${count}"
        ((file_count[$author:$filename_no_ext]=count+1))
      else
        file_count[$author:$filename_no_ext]=1
      fi
      
      # 创建作者文件夹
      mkdir -p "Original/$author"
      # 下载文件
      file_path="Original/$author/$filename_no_ext.${filename##*.}"
      curl -L -o "$file_path" "$url"
      
      # 准备README内容
      README_CONTENT="${README_CONTENT}\n- **${filename_no_ext}**: Converted from [${author} ${filename_no_ext}](${url})"
      
      # 提取非注释行中的 hostname 信息
      hostnames=$(grep -v '^#' "$file_path" | grep 'hostname = ' | awk -F'hostname = ' '{print $2}' | tr '\n' ', ' | sed 's/, $//')
      # 生成注释内容
      comment="# ${filename_no_ext} // ${hostnames}"
      
      # 将文件信息追加到 FILES_LIST
      FILES_LIST="${FILES_LIST}\n${file_path};${author};${filename_no_ext};${comment}"
    done < Links/Modules-Links.txt
