name: Convert Modules Simply (Old)

on:
  #schedule:
  #  - cron: '0 0 * * *' # 每天执行一次
  workflow_dispatch: # 手动触发

jobs:
  update-snippet:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download snippets
      run: |
        mkdir -p Original/ddgksf2013 Original/fmz200 Original/Lodepuly Original/RuCu6 Original/ZenmoFeiShi
        curl -L -o Original/ddgksf2013/SmzdmAds.conf https://github.com/ddgksf2013/Rewrite/raw/master/AdBlock/SmzdmAds.conf
        curl -L -o Original/ddgksf2013/StartUp.conf https://raw.githubusercontent.com/ddgksf2013/Rewrite/master/AdBlock/StartUp.conf
        curl -L -o Original/fmz200/chongxie.txt https://github.com/fmz200/wool_scripts/raw/main/QuantumultX/rewrite/chongxie.txt
        curl -L -o Original/Lodepuly/Remove_ads_by_keli.plugin https://gitlab.com/lodepuly/vpn_tool/-/raw/master/Tool/Loon/Plugin/Remove_ads_by_keli.plugin
        curl -L -o Original/RuCu6/Amap.snippet https://github.com/RuCu6/QuanX/raw/main/Rewrites/Cube/amap.snippet
        curl -L -o Original/RuCu6/Bilibili.snippet https://github.com/RuCu6/QuanX/raw/main/Rewrites/Cube/bilibili.snippet
        curl -L -o Original/RuCu6/MyBlockAds.conf https://github.com/RuCu6/QuanX/raw/main/Rewrites/MyBlockAds.conf
        curl -L -o Original/RuCu6/weibo.snippet https://github.com/RuCu6/QuanX/raw/main/Rewrites/Cube/weibo.snippet
        curl -L -o Original/ZenmoFeiShi/Didichuxing.snippet https://github.com/ZenmoFeiShi/Qx/raw/main/Didichuxing.snippet
        curl -L -o Original/ZenmoFeiShi/Pinduoduo.snippet https://github.com/ZenmoFeiShi/Qx/raw/main/Pinduoduo.snippet
        curl -L -o Original/ZenmoFeiShi/Smzdm.snippet https://github.com/ZenmoFeiShi/Qx/raw/main/Smzdm.snippet

    - name: Prepare Replacement Variables
      id: prepare-replacement
      run: |
        # 定义文件和注释前缀的映射
        declare -A files
        files["Original/RuCu6/Amap.snippet"]="Amap RuCu6"
        files["Original/RuCu6/Bilibili.snippet"]="Bilibili RuCu6"
        files["Original/fmz200/chongxie.txt"]="Chongxie fmz200"
        files["Original/ZenmoFeiShi/Didichuxing.snippet"]="Didichuxing ZenmoFeiShi"
        files["Original/Lodepuly/Remove_ads_by_keli.plugin"]="RemoveAdsByKeli Lodepuly"
        files["Original/RuCu6/MyBlockAds.conf"]="MyBlockAds RuCu6"
        files["Original/ZenmoFeiShi/Pinduoduo.snippet"]="Pinduoduo ZenmoFeiShi"
        files["Original/ddgksf2013/SmzdmAds.conf"]="SmzdmAds ddgksf2013"
        files["Original/ddgksf2013/StartUp.conf"]="StartUp ddgksf2013"
        files["Original/RuCu6/weibo.snippet"]="Weibo RuCu6"
        files["Original/ZenmoFeiShi/Smzdm.snippet"]="Smzdm ZenmoFeiShi"

        # 循环处理每个文件
        for file in "${!files[@]}"; do
          # 提取文件名和作者
          IFS=' ' read -r filename author <<< "${files[$file]}"
          # 提取非注释行中的 hostname 信息
          hostnames=$(grep -v '^#' "$file" | grep 'hostname = ' | awk -F'hostname = ' '{print $2}' | tr '\n' ', ' | sed 's/, $//')
          # 生成注释内容
          comment="# ${filename} // ${hostnames}"
          # 生成环境变量名，替换空格为下划线并确保它是合法的
          varname="${author}_${filename// /_}_COMMENT"  
          # 输出到环境变量
          echo "$varname=$comment" >> $GITHUB_ENV
        done

    - name: Convert snippets
      run: |
        mkdir -p Modules/Surge Modules/Loon
        bash Convert-Modules.sh "Original/RuCu6/Amap.snippet" "RuCu6_Amap" "$RuCu6_Amap_COMMENT"
        bash Convert-Modules.sh "Original/RuCu6/Bilibili.snippet" "RuCu6_Bilibili" "$RuCu6_Bilibili_COMMENT"
        bash Convert-Modules.sh "Original/fmz200/chongxie.txt" "fmz200_Chongxie" "$fmz200_Chongxie_COMMENT"
        bash Convert-Modules.sh "Original/ZenmoFeiShi/Didichuxing.snippet" "ZenmoFeiShi_Didichuxing" "$ZenmoFeiShi_Didichuxing_COMMENT"
        bash Convert-Modules.sh "Original/Lodepuly/Remove_ads_by_keli.plugin" "Lodepuly_RemoveAdsByKeli" "$Lodepuly_RemoveAdsByKeli_COMMENT"
        bash Convert-Modules.sh "Original/RuCu6/MyBlockAds.conf" "RuCu6_MyBlockAds" "$RuCu6_MyBlockAds_COMMENT"
        bash Convert-Modules.sh "Original/ZenmoFeiShi/Pinduoduo.snippet" "ZenmoFeiShi_Pinduoduo" "$ZenmoFeiShi_Pinduoduo_COMMENT"
        bash Convert-Modules.sh "Original/ddgksf2013/SmzdmAds.conf" "ddgksf2013_SmzdmAds" "$ddgksf2013_SmzdmAds_COMMENT"
        bash Convert-Modules.sh "Original/ddgksf2013/StartUp.conf" "ddgksf2013_StartUp" "$ddgksf2013_StartUp_COMMENT"
        bash Convert-Modules.sh "Original/RuCu6/weibo.snippet" "RuCu6_Weibo" "$RuCu6_Weibo_COMMENT"
        bash Convert-Modules.sh "Original/ZenmoFeiShi/Smzdm.snippet" "ZenmoFeiShi_Smzdm" "$ZenmoFeiShi_Smzdm_COMMENT"

    - name: Create README in Modules directory
      run: |
        echo "# Modules for Surge and Loon" > Modules/README.md
        echo "" >> Modules/README.md
        echo "This directory contains converted modules from various sources, compatible with Surge and Loon." >> Modules/README.md
        echo "" >> Modules/README.md
        echo "## Sources" >> Modules/README.md
        echo "" >> Modules/README.md
    
        echo "- **Amap**: Converted from [RuCu6 Amap.snippet](https://github.com/RuCu6/QuanX/raw/main/Rewrites/Cube/amap.snippet)" >> Modules/README.md
        echo "- **Bilibili**: Converted from [RuCu6 Bilibili.snippet](https://github.com/RuCu6/QuanX/raw/main/Rewrites/Cube/bilibili.snippet)" >> Modules/README.md
        echo "- **Chongxie**: Converted from [fmz200 chongxie.txt](https://github.com/fmz200/wool_scripts/raw/main/QuantumultX/rewrite/chongxie.txt)" >> Modules/README.md
        echo "- **Didichuxing**: Converted from [ZenmoFeiShi Didichuxing.snippet](https://github.com/ZenmoFeiShi/Qx/raw/main/Didichuxing.snippet)" >> Modules/README.md
        echo "- **RemoveAdsByKeli**: Converted from [Lodepuly Remove_ads_by_keli.plugin](https://gitlab.com/lodepuly/vpn_tool/-/raw/master/Tool/Loon/Plugin/Remove_ads_by_keli.plugin)" >> Modules/README.md
        echo "- **MyBlockAds**: Converted from [RuCu6 MyBlockAds.conf](https://github.com/RuCu6/QuanX/raw/main/Rewrites/MyBlockAds.conf)" >> Modules/README.md
        echo "- **Pinduoduo**: Converted from [ZenmoFeiShi Pinduoduo.snippet](https://github.com/ZenmoFeiShi/Qx/raw/main/Pinduoduo.snippet)" >> Modules/README.md
        echo "- **SmzdmAds**: Converted from [ddgksf2013 SmzdmAds.conf](https://github.com/ddgksf2013/Rewrite/raw/master/AdBlock/SmzdmAds.conf)" >> Modules/README.md
        echo "- **StartUp**: Converted from [ddgksf2013 StartUp.conf](https://raw.githubusercontent.com/ddgksf2013/Rewrite/master/AdBlock/StartUp.conf)" >> Modules/README.md
        echo "- **Weibo**: Converted from [RuCu6 Weibo.snippet](https://github.com/RuCu6/QuanX/raw/main/Rewrites/Cube/weibo.snippet)" >> Modules/README.md
        echo "- **ZenmoFeiShi_Smzdm**: Converted from [ZenmoFeiShi Smzdm.snippet](https://github.com/ZenmoFeiShi/Qx/raw/main/Smzdm.snippet)" >> Modules/README.md

    - name: Commit and Push changes
      run: |
        git config --local user.name "ifflagged"
        git config --local user.email "qibo.sign@outlook.com"
        git add .
        if git diff --cached --quiet; then
          echo "No changes detected"
        else
          git commit -m "Update Modules"
          git push
        fi

    - name: Send TG Notification
      run: |
        # Check if there is a previous commit
        if git rev-parse --verify HEAD^1 >/dev/null 2>&1; then
          UPDATED_FILES=$(git diff --name-only HEAD^1 HEAD Modules/)
        else
          UPDATED_FILES=$(git diff --name-only HEAD Modules/)
        fi
        
        if [ -n "$UPDATED_FILES" ]; then
          MESSAGE="The following files have been updated:\n$UPDATED_FILES"
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage -d chat_id=${{ secrets.TG_ID }} -d text="$MESSAGE"
        else
          echo "No files were updated, no notification sent."
        fi
