name: Get Specific Files from Private Repo

on:
  schedule:
    - cron: '0 22 * * *' # 每天执行一次
  workflow_dispatch:     # 手动触发

jobs:
  get-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2

      - name: Checkout the private repository
        uses: actions/checkout@v2
        with:
          repository: ifflagged/ShalalaLala  # 私有库的路径
          token: ${{ secrets.PERSONAL_TOKENS }}  # 使用你的 GitHub Token
          path: private-repo  # 临时路径

      - name: Copy specific files
        run: |
          mkdir -p Modules/Surge/Kelee/
          mkdir -p Modules/Loon/Kelee/
          cp private-repo/Modules/Surge/Kelee/高德地图去广告.sgmodule Modules/Surge/Kelee/高德地图去广告.sgmodule
          cp private-repo/Modules/Surge/Kelee/滴滴出行去广告.sgmodule Modules/Surge/Kelee/滴滴出行去广告.sgmodule
          cp private-repo/Modules/Surge/Kelee/航旅纵横去广告.sgmodule Modules/Surge/Kelee/航旅纵横去广告.sgmodule
          cp private-repo/Modules/Loon/Kelee/高德地图去广告.plugin Modules/Surge/Kelee/高德地图去广告.plugin
          cp private-repo/Modules/Loon/Kelee/滴滴出行去广告.plugin Modules/Surge/Kelee/滴滴出行去广告.plugin
          cp private-repo/Modules/Loon/Kelee/航旅纵横去广告.plugin Modules/Surge/Kelee/航旅纵横去广告.plugin

      - name: Check for changes
        id: changes
        run: |
          git config --local user.name "ifflagged"
          git config --local user.email "qibo.sign@outlook.com"
          git add.
          git diff --cached --quiet || echo "Changes detected" # 检查是否有更改

      - name: Commit changes if any
        if: steps.changes.outputs.result == 'Changes detected'
        run: |
          git commit -m "Update Some modules"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ifflagged/BaDaBaBaBa.git

      - name: Send Telegram notification if changes were committed
        if: steps.changes.outputs.result == 'Changes detected'
        run: |
          # 获取最近的提交中的更新文件
          if git rev-parse --verify HEAD^1 >/dev/null 2>&1; then
            UPDATED_FILES=$(git diff --name-only HEAD^1 HEAD Modules/)
          else
            UPDATED_FILES=$(git diff --name-only HEAD Modules/)
          fi

          # 如果有更新文件，则发送通知
          if [ -n "$UPDATED_FILES" ]; then
            MESSAGE="The following files have been updated:\n"
            GITHUB_URL="https://github.com/ifflagged/BaDaBaBaBa/blob/main/"
            while read -r file; do
              file_url="${GITHUB_URL}${file}"
              MESSAGE="${MESSAGE}[${file}](${file_url})\n"
            done <<< "$UPDATED_FILES"

            curl -s -X POST https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage \
              -d chat_id=${{ secrets.TG_ID }} \
              -d text="$(echo -e "$MESSAGE")" \
              -d parse_mode=Markdown
          else
            echo "No files were updated, no notification sent."
          fi
