name: Get Private Files

on:
  schedule:
    - cron: '0 23 * * *'   # 每天早上7点（北京时间）
    - cron: '0 13 * * *'   # 每天下午9点（北京时间）
  workflow_dispatch:       # 手动触发

jobs:
  get-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2

      - name: Checkout the private repository
        uses: actions/checkout@v2
        with:
          repository: ifflagged/ShalalaLala  # 私有库的路径
          token: ${{ secrets.PERSONAL_TOKENS }}  # 使用你的 GitHub Token
          path: private-repo  # 临时路径

      - name: Copy specific files
        run: |
          mkdir -p Modules/Surge
          mkdir -p Modules/Loon
          mkdir -p Modules/Shadowrocket
          cp private-repo/Modules/Surge/*.sgmodule Modules/Surge/
          cp private-repo/Modules/Loon/*.plugin Modules/Loon/
          cp private-repo/Modules/Shadowrocket/*.srmodule Modules/Shadowrocket/

      - name: Verify copied files
        run: |
          echo "Files in Modules/Surge:"
          ls -l Modules/Surge/
          echo "Files in Modules/Loon:"
          ls -l Modules/Loon/
          echo "Files in Modules/Shadowrocket:"
          ls -l Modules/Shadowrocket/

      - name: Remove private-repo folder
        run: rm -rf private-repo

      - name: Check for changes
        id: changes
        run: |
          git add .
          if git diff --cached --quiet; then
            echo "No changes detected"
            echo "::set-output name=result::No changes"
          else
            echo "Changes detected"
            echo "::set-output name=result::Changes detected"
          fi

      - name: Commit changes if any
        if: steps.changes.outputs.result == 'Changes detected'
        run: |
          git config --local user.name "ifflagged"
          git config --local user.email "qibo.sign@outlook.com"
          git commit -m "Update generated files"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ifflagged/BaDaBaBaBa.git

      - name: Send TG Notification if changes were committed
        if: steps.changes.outputs.result == 'Changes detected'
        run: |
          UPDATED_FILES=$(git diff --name-only HEAD^ HEAD Modules/)
          if [ -n "$UPDATED_FILES" ]; then
            MESSAGE="The following files have been updated:\n"
            GITHUB_URL="https://github.com/ifflagged/BaDaBaBaBa/blob/main/"
            while IFS= read -r file; do
              # 去掉 'Modules/' 前缀
              display_name="${file#Modules/}"
              # 生成完整链接
              file_url="${GITHUB_URL}${file}"
              # 生成 markdown 格式的超链接
              MESSAGE="${MESSAGE}[${display_name}](${file_url})\n"
            done <<< "$UPDATED_FILES"

            # 使用 echo -e 处理换行符并发送通知
            curl -s -X POST https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage \
              -d chat_id=${{ secrets.TG_ID }} \
              -d text="$(echo -e "$MESSAGE")" \
              -d parse_mode=Markdown
          else
            echo "No files were updated, no notification sent."
          fi
