name: Get Specific Files from Private Repo

on:
  schedule:
    - cron: '0 23 * * *'    # 每天早上7点（上海时间）
    - cron: '0 13 * * *'    # 每天下午9点（上海时间）
  workflow_dispatch:       # Manual trigger

jobs:
  get-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2

      - name: Checkout the private repository
        uses: actions/checkout@v2
        with:
          repository: ifflagged/ShalalaLala  # 私有库的路径
          token: ${{ secrets.PERSONAL_TOKENS }}  # 使用你的 GitHub Token
          path: private-repo  # 临时路径

      - name: Copy specific files
        run: |
          mkdir -p Modules/Surge
          mkdir -p Modules/Loon
          mkdir -p Modules/Shadowrocket
          cp private-repo/Modules/Surge/Tools.sgmodule Modules/Surge/Tools.sgmodule
          cp private-repo/Modules/Loon/Tools.plugin Modules/Loon/Tools.plugin
          cp private-repo/Modules/Shadowrocket/Tools.sgmodule Modules/Shadowrocket/Tools.sgmodule

      - name: Verify copied files
        run: |
          echo "Files in Modules/Surge:"
          ls -l Modules/Surge/
          echo "Files in Modules/Loon:"
          ls -l Modules/Loon/
          echo "Files in Modules/Shadowrocket:"
          ls -l Modules/Shadowrocket/

      - name: Check for changes
        id: changes
        run: |
          git config --local user.name "ifflagged"
          git config --local user.email "qibo.sign@outlook.com"
          git add Modules/*/Kelee/*
          git status
          if git diff --cached --quiet; then
            echo "No changes detected."
            echo "changes=false" >> $GITHUB_ENV
          else
            echo "Changes detected."
            echo "changes=true" >> $GITHUB_ENV
          fi

      - name: Commit changes if any
        if: env.changes == 'true'
        run: |
          git commit -m "Update merged modules"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ifflagged/BaDaBaBaBa.git

      - name: Send Telegram notification if changes were committed
        if: env.changes == 'true'
        run: |
          # 获取最近的提交中的更新文件
          if git rev-parse --verify HEAD^1 >/dev/null 2>&1; then
            UPDATED_FILES=$(git diff --name-only HEAD^1 HEAD Modules/)
          else
            UPDATED_FILES=$(git diff --name-only HEAD Modules/)
          fi

          # 如果有更新文件，则发送通知
          if [ -n "$UPDATED_FILES" ]; then
            MESSAGE="The following files have been updated:\n"
            GITHUB_URL="https://github.com/ifflagged/BaDaBaBaBa/blob/main/"
            while read -r file; do
              file_url="${GITHUB_URL}${file}"
              MESSAGE="${MESSAGE}[${file}](${file_url})\n"
            done <<< "$UPDATED_FILES"

            curl -s -X POST https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage \
              -d chat_id=${{ secrets.TG_ID }} \
              -d text="$(echo -e "$MESSAGE")" \
              -d parse_mode=Markdown
          else
            echo "No files were updated, no notification sent."
          fi
