name: Download Loon Plugin

on:
  push:
    branches:
      - main

jobs:
  download_plugin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # 或其他你需要的版本

      - name: Install axios
        run: npm install axios

      - name: Create Test directory
        run: mkdir -p Test

      - name: Download Plugin using Loon simulation
        run: |
          echo "const fs = require('fs');
          const axios = require('axios');

          async function download() {
            const url = 'https://kelee.one/Tool/Loon/Plugin/BlockAdvertisers.plugin';
            const path = 'Test/BlockAdvertisers.plugin';
            const response = await axios.get(url, {
              responseType: 'arraybuffer',
              headers: {
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36',
                'Accept': '*/*',
                'Referer': 'https://kelee.one/'
              }
            });
            fs.writeFileSync(path, response.data);
            console.log('Download complete: ' + path);
          }

          download().catch(console.error);" > download.js

          node download.js

      - name: List files in Test directory
        run: ls -l Test

      - name: Commit and push the downloaded plugin
        run: |
          git config --local user.name "ifflagged"
          git config --local user.email "qibo.sign@outlook.com"
          git add Test/BlockAdvertisers.plugin
          git commit -m "Add BlockAdvertisers.plugin" || echo "No changes to commit"
          git push || echo "No changes to push"
