name: Download Loon Plugin via Headless Browser

on:
  workflow_dispatch:

jobs:
  download-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Download Plugin with Puppeteer
        run: |
          node -e "
          const fs = require('fs');
          const puppeteer = require('puppeteer');
          (async () => {
            const browser = await puppeteer.launch();
            const page = await browser.newPage();
            await page.setUserAgent('Mozilla/5.0 (iPhone; CPU iPhone OS 14_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 Loon/2.1.3');
            await page.goto('https://www.nsloon.com/openloon/import?plugin=https://kelee.one/Tool/Loon/Plugin/BlockAdvertisers.plugin');
            
            // 确保页面加载完成后再下载内容
            const content = await page.content();
            fs.writeFileSync('Plugins/BlockAdvertisers.plugin', content);
            
            await browser.close();
          })();
          "

      - name: Commit and push changes if downloaded
        run: |
          git config --local user.name "ifflagged"
          git config --local user.email "qibo.sign@outlook.com"
          git add Plugins/BlockAdvertisers.plugin
          git commit -m "Download Loon Plugin with Puppeteer"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
