name: Download Loon Plugin Directly

on:
  workflow_dispatch:

jobs:
  download-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download Loon Plugin directly
        run: |
          mkdir -p Plugins
          curl -L -o Plugins/BlockAdvertisers.plugin \
            -H "User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 14_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 Loon/2.1.3" \
            "https://kelee.one/Tool/Loon/Plugin/BlockAdvertisers.plugin"

      - name: Commit and push changes if downloaded
        run: |
          git config --local user.name "ifflagged"
          git config --local user.email "qibo.sign@outlook.com"
          git add Plugins/BlockAdvertisers.plugin
          git commit -m "Download Loon Plugin directly"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
