name: Download Plugin

on:
  push:
    branches:
      - main

jobs:
  download-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create TEST directory
        run: mkdir -p TEST

      - name: Download Plugin with custom User-Agent
        run: |
          curl -A "Surge Mac/2985" -L -o TEST/BlockAdvertisers.plugin "https://kelee.one/Tool/Loon/Plugin/BlockAdvertisers.plugin"

      - name: Verify download
        run: ls -l TEST

      - name: Commit and push changes if downloaded
        run: |
          git config --local user.name "ifflagged"
          git config --local user.email "qibo.sign@outlook.com"
          git add .
          git commit -m "Download Loon Plugin with Custom User-Agent"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
