name: Delete Unwanted Files

on:
  workflow_dispatch:

jobs:
  delete-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Delete .sgmodule and .plugin files in root directory
        run: |
          find . -maxdepth 1 -name "*.sgmodule" -type f -delete
          find . -maxdepth 1 -name "*.plugin" -type f -delete

      - name: Commit changes
        run: |
          git config --local user.name "ifflagged"
          git config --local user.email "qibo.sign@outlook.com"
          git add -u
          git commit -m "Delete unwanted .sgmodule and .plugin files" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push origin main
