name: Merge Modules

on:
  schedule:
    - cron: '0 0 * * *' # 每天执行一次
  workflow_dispatch: # 手动触发

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run merge script
        run: |
          python Modules-Merge.py Modules-*.txt

      - name: Commit and push changes
        run: |
          git config --local user.name "ifflagged"
          git config --local user.email "qibo.sign@outlook.com"
          git add Modules/*
          git commit -m "Update merged modules" || echo "No changes to commit"
          git push
